on:
  push:
      branches:
        - master
        - development
      paths:
        - "DataSpecs/**/*.json"
jobs:
  format-json:
    runs-on: ubuntu-latest
    permissions: write-all
    steps:
      - uses: actions/checkout@v4
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
      - uses: actions/setup-python@v4
        with:
          python-version: "3.10"
      - name: Run formatter
        shell: bash
        if: env.is-auto-commit != true
        run: |
          echo "is-auto-commit=true" >> $GITHUB_ENV
          git show --name-only HEAD~1 | grep "\.json" | xargs -I% python3 -m json.tool % %
          git config --global user.email "bot@example.com"
          git config --global user.name "Action Bot"
          git commit -am "Run JSON formatter"
          git push
