on: [push]
jobs:
  format-json:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v4
        with:
          python-version: "3.10"
      - run: ls -l 'json/*.json' | xargs -I % python3 -m json.tool % > %
